// First-run seed data, migrated out of Bid_Proposal_Manager_2026 (1).html.
// After first load the live copy lives in localStorage - editing this file only
// affects a browser that has never opened the app (or one that has been reset).
// Schema 4 field names: products[] (was railing/productType), assignedHrs (was scopeHrs).
// Schema 9 status names: "Submitted to review" (was "Submitted"). This file is
// stamped with the current schema by Store.freshDB, so no migration runs over
// it - status names here have to be the current ones.
window.SEED_REGIONS = [
  "Adams County",
  "Allegheny County",
  "Armstrong County",
  "Beaver County",
  "Bennock County",
  "Blair County",
  "Bucks County",
  "Butler County",
  "Cambria County",
  "Clarion County",
  "Columbia County",
  "Columbiana County",
  "Crawford County",
  "Cuyahoga County",
  "Dauphin County",
  "Erie County",
  "Fairfax County",
  "Fayette County",
  "Forest County",
  "Garrett County",
  "Greene County",
  "Indiana County",
  "Jefferson County",
  "Lancaster County",
  "Lawrence County",
  "Lebanon County",
  "Mercer County",
  "Ohio County",
  "Prince George's County",
  "Prince William County",
  "Randolph County",
  "Somerset County",
  "Spotsylvania County",
  "Venango County",
  "Washington County",
  "Westmoreland County"
];

window.SEED_BIDS = [
 {
  "id": 1,
  "sr": 1,
  "portal": "PlanHub",
  "project": "Murray Tower Rehabilitation",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Galvanized handrails, guardrails and wall mounted Handrails"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": 886,
  "price": 485000,
  "assignedHrs": 9,
  "estHrs": 27,
  "bidHrs": 9,
  "totalHrs": 45,
  "dueDate": "2026-07-01",
  "status": "Submitted to review",
  "won": "",
  "link": "",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 2,
  "sr": 2,
  "portal": "PlanHub",
  "project": "229 Houston Road Renovations",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Aluminum Railing & Guardrail, Aluminum Railing & Guardrail with stainless steel mesh panel, Wall mounted handrails"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": 518,
  "price": 99500,
  "assignedHrs": 6,
  "estHrs": 27,
  "bidHrs": 2,
  "totalHrs": 35,
  "dueDate": "2026-07-03",
  "status": "Submitted to review",
  "won": "No",
  "link": "",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 3,
  "sr": 3,
  "portal": "PlanHub",
  "project": "Christ Church at Grove Farm",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Galvanized guardrail with mesh infill / Galvanized guardrail with mesh infill & handrail / Galvanized wall mounted handrail"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": 398,
  "price": 312500,
  "assignedHrs": 4.5,
  "estHrs": 15.5,
  "bidHrs": 6,
  "totalHrs": 26,
  "dueDate": "2026-07-26",
  "status": "Submitted to review",
  "won": "",
  "link": "https://subcontractor.planhub.com/leads/details/564911",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 4,
  "sr": 4,
  "portal": "BuildingConnect",
  "project": "CVS Keystone",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [],
  "material": "Carbon steel",
  "engineer": "",
  "lf": 230,
  "price": 108000,
  "assignedHrs": 2,
  "estHrs": 0,
  "bidHrs": 2,
  "totalHrs": 4,
  "dueDate": "2026-07-29",
  "status": "Submitted to review",
  "won": "",
  "link": "",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 5,
  "sr": 5,
  "portal": "ConstructConnect",
  "project": "Washington County Public Safety Building",
  "region": "Washington County",
  "inRegion": true,
  "products": [
   "Stainless steel cable railing / Galv steel picket type railing"
  ],
  "material": "Stainless steel",
  "engineer": "",
  "lf": 1464,
  "price": 742000,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-07-29",
  "status": "Submitted to review",
  "won": "",
  "link": "https://app.constructconnect.com/project/863523",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 6,
  "sr": 6,
  "portal": "ConstructConnect",
  "project": "Blackhawk Intermediate School",
  "region": "Beaver County",
  "inRegion": true,
  "products": [
   "Steel Tube Guardrail with Handrail"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": 89,
  "price": 65000,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-08-06",
  "status": "In Progress",
  "won": "",
  "link": "https://app.constructconnect.com/project/864977",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 7,
  "sr": 7,
  "portal": "PlanHub",
  "project": "Duke Petroleum",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Steel Tube Guardrail with Handrail"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": 36,
  "price": 40000,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-07-29",
  "status": "Submitted to review",
  "won": "",
  "link": "https://subcontractor.planhub.com/leads/details/569091",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 8,
  "sr": 8,
  "portal": "ConstructConnect",
  "project": "Public Safety Building Elevator Addition and Alterations",
  "region": "Cambria County",
  "inRegion": true,
  "products": [
   "Aluminum Guardrail with handrail with cable railing, wood handrail"
  ],
  "material": "Aluminum, Wood",
  "engineer": "",
  "lf": 87.27,
  "price": 86000,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-07-31",
  "status": "Submitted to review",
  "won": "",
  "link": "https://app.constructconnect.com/project/6175244",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 9,
  "sr": 9,
  "portal": "ConstructConnect",
  "project": "E24-010 Radnor-3401 Blvd of the Allies",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Steel Guardrail with handrail"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": 1600,
  "price": 0,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-08-13",
  "status": "In Progress",
  "won": "",
  "link": "https://app.constructconnect.com/project/6705729",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 10,
  "sr": 10,
  "portal": "ConstructConnect",
  "project": "Flagstaff Hill Pathway - Rebid - All Trades",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Steel Handrail"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": 66,
  "price": 0,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-08-08",
  "status": "In Progress",
  "won": "",
  "link": "https://app.constructconnect.com/project/865522",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 11,
  "sr": 11,
  "portal": "BuildingConnected",
  "project": "Chick Fil A",
  "region": "Indiana County",
  "inRegion": true,
  "products": [
   "Aluminum Guardrail"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": 61,
  "price": 0,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-08-12",
  "status": "In Progress",
  "won": "",
  "link": "https://app.buildingconnected.com/opportunities/6a454fcc",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 12,
  "sr": 12,
  "portal": "PlanHub",
  "project": "S & T Bank",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Glass Railing"
  ],
  "material": "Glass",
  "engineer": "",
  "lf": 0,
  "price": 0,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-08-13",
  "status": "In Progress",
  "won": "",
  "link": "https://subcontractor.planhub.com/leads/details/572413",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 13,
  "sr": 13,
  "portal": "PlanHub",
  "project": "Discount Tire",
  "region": "Fayette County",
  "inRegion": true,
  "products": [],
  "material": "",
  "engineer": "",
  "lf": 0,
  "price": 0,
  "assignedHrs": 0,
  "estHrs": 0,
  "bidHrs": 0,
  "totalHrs": 0,
  "dueDate": "2026-08-23",
  "status": "In Progress",
  "won": "",
  "link": "https://subcontractor.planhub.com/leads/details/572783",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 14,
  "sr": 1,
  "portal": "PlanHub",
  "project": "UD Chiller Capacity and Controls Upgrade Pittsburgh VA Medical Center",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Powdercoated Aluminum Handrail and guardrail"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 15,
  "sr": 2,
  "portal": "PlanHub",
  "project": "West Co Local Br Preservation",
  "region": "",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 16,
  "sr": 3,
  "portal": "PlanHub",
  "project": "Zelienople Borough - Public Library New Building Construction",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Insufficient scope"
  ],
  "material": "Galvanized Steel",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-26",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 17,
  "sr": 4,
  "portal": "PennBid",
  "project": "Paxtang Borough Special Provisions for Contract MS-944",
  "region": "Dauphin County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 18,
  "sr": 5,
  "portal": "PennBid",
  "project": "Hoffman Homes for Youth, Adams County",
  "region": "Adams County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 19,
  "sr": 6,
  "portal": "PennBid",
  "project": "Indiana County Conservation District",
  "region": "Indiana County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 20,
  "sr": 7,
  "portal": "PennBid",
  "project": "City of Lancaster, Lancaster County",
  "region": "Lancaster County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 21,
  "sr": 8,
  "portal": "PennBid",
  "project": "DQ 250 South Stuart Ave Construction",
  "region": "Bennock County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 22,
  "sr": 9,
  "portal": "PlanHub",
  "project": "Lincoln Corner Plaza - Building 300",
  "region": "Westmoreland County",
  "inRegion": true,
  "products": [
   "Insufficient drawings"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-26",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 23,
  "sr": 10,
  "portal": "PlanHub",
  "project": "Sheetz - North Huntingdon, PA",
  "region": "Westmoreland County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 24,
  "sr": 11,
  "portal": "PlanHub",
  "project": "New Hope Borough, Bucks County",
  "region": "Bucks County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 25,
  "sr": 12,
  "portal": "PennBid",
  "project": "Upper Uwchlan Township Building Additions & Alterations",
  "region": "Lancaster County",
  "inRegion": false,
  "products": [
   "Powdercoated Aluminum Handrail and guardrail"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-24",
  "status": "Completed",
  "comments": "06-12-26 Submitted for Missy's review. 06-16-26 Confirmation received from Missy to proceed for bid",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 26,
  "sr": 13,
  "portal": "PlanHub",
  "project": "Renovation & Addition to Elkins-Randolph County Library",
  "region": "Randolph County",
  "inRegion": false,
  "products": [
   "Galvanized handrails, guardrails"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-08-03",
  "status": "Completed",
  "comments": "06-12-26 Submitted for Missy's review. 06-16-26 Confirmation received from Missy to proceed for bid",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 27,
  "sr": 14,
  "portal": "PennBid",
  "project": "Donegal School District - Powdercoated Handrail and guardrail",
  "region": "Lancaster County",
  "inRegion": false,
  "products": [
   "Powdercoated Handrail and guardrail"
  ],
  "material": "Galvanized Steel",
  "engineer": "",
  "lf": 725,
  "price": null,
  "assignedHrs": 12.5,
  "estHrs": 1,
  "bidHrs": null,
  "totalHrs": 13.5,
  "dueDate": "2026-08-14",
  "status": "Completed",
  "comments": "06-15-26 Submitted for Missy's review. 06-16-26 Confirmation received from Missy to proceed for bid",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 28,
  "sr": 15,
  "portal": "PlanHub",
  "project": "AL - Wrestling Training Center",
  "region": "Blair County",
  "inRegion": false,
  "products": [
   "Insufficient scope"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 29,
  "sr": 16,
  "portal": "PlanHub",
  "project": "Crunch Fitness - Manassas, VA",
  "region": "Prince William County",
  "inRegion": false,
  "products": [
   "Insufficient scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 30,
  "sr": 17,
  "portal": "PlanHub",
  "project": "Public Safety Building Elevator Addition",
  "region": "Cambria County",
  "inRegion": true,
  "products": [
   "Insufficient scope"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": 80,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 31,
  "sr": 18,
  "portal": "PlanHub",
  "project": "Fire & Rescue Station 8",
  "region": "",
  "inRegion": false,
  "products": [
   "Insufficient scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-08-10",
  "status": "Not Started",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 32,
  "sr": 19,
  "portal": "PlanHub",
  "project": "NVCC MAW Building Exterior Replace Exterior Shell",
  "region": "Prince William County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 33,
  "sr": 20,
  "portal": "PlanHub",
  "project": "Advance Auto Parts",
  "region": "Spotsylvania County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 34,
  "sr": 21,
  "portal": "PlanHub",
  "project": "Prayer & Bodywash Facility",
  "region": "Fairfax County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 35,
  "sr": 22,
  "portal": "PennBid",
  "project": "Borough of Saxonburg, Butler County - Rebid of John Ro",
  "region": "Butler County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 36,
  "sr": 23,
  "portal": "PennBid",
  "project": "BARC Developmental Services - BARC Roof Recovery",
  "region": "Bucks County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 37,
  "sr": 24,
  "portal": "PennBid",
  "project": "Doylestown Township Municipal Authority",
  "region": "Bucks County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 38,
  "sr": 26,
  "portal": "PlanHub",
  "project": "Station 1 Renovations And Addition",
  "region": "Lebanon County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 39,
  "sr": 27,
  "portal": "PlanHub",
  "project": "Norfolk Southern Operations Bldg. - Sharon, PA",
  "region": "Mercer County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 40,
  "sr": 28,
  "portal": "PlanHub",
  "project": "Calcutta Clinic",
  "region": "Columbiana County",
  "inRegion": false,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 41,
  "sr": 29,
  "portal": "PennBid",
  "project": "Imperial Volunteer Fire Department",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 42,
  "sr": 30,
  "portal": "PlanHub",
  "project": "Consumer Cellular",
  "region": "Butler County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 43,
  "sr": 31,
  "portal": "PlanHub",
  "project": "Ironworkers Local 549 - Training Facility Expansion",
  "region": "Ohio County",
  "inRegion": false,
  "products": [
   "Galvanized steel with painting"
  ],
  "material": "Galvanized Steel",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-08-02",
  "status": "Not Started",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 44,
  "sr": 32,
  "portal": "PlanHub",
  "project": "Deep Creek Social",
  "region": "Garrett County",
  "inRegion": false,
  "products": [],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-08-02",
  "status": "Not Started",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 45,
  "sr": 33,
  "portal": "PlanHub",
  "project": "New Multi-Purpose Addition - Chagrin Valley Islamic Center",
  "region": "Cuyahoga County",
  "inRegion": false,
  "products": [],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-21",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 46,
  "sr": 34,
  "portal": "BuildingConnected",
  "project": "WSSC Anacostia Depot Reconfiguration",
  "region": "Prince George's County",
  "inRegion": false,
  "products": [
   "Stainless steel perforated panel railing"
  ],
  "material": "Stainless steel",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-19",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 47,
  "sr": 36,
  "portal": "PlanHub",
  "project": "7 Brew Hermitage, PA",
  "region": "Mercer County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 48,
  "sr": 37,
  "portal": "ConstructConnect",
  "project": "Washington County Public Safety Building - All Trades",
  "region": "Washington County",
  "inRegion": true,
  "products": [
   "Stainless steel cable railing, Galv steel picket type railing"
  ],
  "material": "Stainless steel",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-29",
  "status": "In Progress",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false,
  "flags": {
   "lfTBD": true
  }
 },
 {
  "id": 49,
  "sr": 38,
  "portal": "SmartBid",
  "project": "Imperial VFD Station 2 Expansion",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 50,
  "sr": 39,
  "portal": "PlanHub",
  "project": "7 Brew - Bethel Park",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 51,
  "sr": 40,
  "portal": "PennBid",
  "project": "Pennsylvania Western University, Clarion County",
  "region": "Clarion County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 52,
  "sr": 41,
  "portal": "PlanHub",
  "project": "Dollar Tree",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 53,
  "sr": 42,
  "portal": "PlanHub",
  "project": "Marshalls - Robinson Town Centre",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 54,
  "sr": 43,
  "portal": "PlanHub",
  "project": "Sierra - Robinson Town Centre",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 55,
  "sr": 44,
  "portal": "ConstructConnect",
  "project": "PGH Airport - Airside Concourse Renovations Phase 2",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "(Glass with metal panel) Limited scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 56,
  "sr": 44,
  "portal": "ConstructConnect",
  "project": "Canonsburg Senior Center Renovations",
  "region": "Washington County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 57,
  "sr": 45,
  "portal": "PlanHub",
  "project": "Longhorn Steakhouse - Hermitage, PA",
  "region": "Mercer County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 58,
  "sr": 46,
  "portal": "BuildingConnected",
  "project": "Longhorn- Hermitage, PA",
  "region": "Mercer County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 59,
  "sr": 47,
  "portal": "PlanHub",
  "project": "Visionworks #651-Lafayette Plaza",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 60,
  "sr": 48,
  "portal": "PlanHub",
  "project": "Walmart 2540.1010 - Clarion, PA",
  "region": "Clarion County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 61,
  "sr": 49,
  "portal": "PennBid",
  "project": "Rostraver Township, Westmoreland County - Annex Building",
  "region": "Westmoreland County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 62,
  "sr": 50,
  "portal": "ConstructConnect",
  "project": "Canonsburg_Senior_Center_",
  "region": "Washington County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 63,
  "sr": 51,
  "portal": "PlanHub",
  "project": "Duke Petroleum",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Steel Guardrail with handrail"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-29",
  "status": "In Progress",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 64,
  "sr": 52,
  "portal": "ConstructConnect",
  "project": "Gobbler Knob Visitors Center - Rebid",
  "region": "Jefferson County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 65,
  "sr": 53,
  "portal": "PlanHub",
  "project": "Visionworks #651-Lafayette Plaza-N Fayette",
  "region": "Fayette County",
  "inRegion": true,
  "products": [
   "No-scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 66,
  "sr": 54,
  "portal": "ConstructConnect",
  "project": "Public Safety Building Elevator Addition",
  "region": "Cambria County",
  "inRegion": true,
  "products": [
   "Aluminum Guardrail with handrail with cable railing, wood handrail"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-07-31",
  "status": "In Progress",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 67,
  "sr": 55,
  "portal": "ConstructConnect",
  "project": "E24-010 Radnor-3401 Blvd of the Allies",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Steel Guardrail with handrail"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-08-13",
  "status": "In Progress",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 68,
  "sr": 56,
  "portal": "ConstructConnect",
  "project": "Flagstaff Hill Pathway - Rebid - All Trades",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Steel Handrails"
  ],
  "material": "Carbon steel",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "In Progress",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 69,
  "sr": 57,
  "portal": "ConstructConnect",
  "project": "USPS - Erie, PA - Retail Lobby Modernization",
  "region": "Erie County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 70,
  "sr": 58,
  "portal": "ConstructConnect",
  "project": "Canonsburg Senior Center Renovations",
  "region": "Washington County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 71,
  "sr": 59,
  "portal": "BuildingConnect",
  "project": "Chick Fil A - Indiana, PA",
  "region": "Indiana County",
  "inRegion": true,
  "products": [
   "Aluminum Guardrail"
  ],
  "material": "Aluminum",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 72,
  "sr": 60,
  "portal": "PlanHub",
  "project": "West Mifflin Self Storage PA",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 73,
  "sr": 61,
  "portal": "ConstructConnect",
  "project": "Voeghtly Street Capital",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 74,
  "sr": 62,
  "portal": "ConstructConnect",
  "project": "2026 Henderson Taylor Community Park Improvement",
  "region": "Mercer County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 75,
  "sr": 63,
  "portal": "ConstructConnect",
  "project": "Xtreme Skate Park Demolition and Reconstruction",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 76,
  "sr": 64,
  "portal": "ConstructConnect",
  "project": "FR 321 Kinzua Creek AOP Replacement",
  "region": "Jefferson County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 77,
  "sr": 65,
  "portal": "PlanHub",
  "project": "Westmoreland Transit Bus Wash Rehabilitation",
  "region": "Westmoreland County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 78,
  "sr": 66,
  "portal": "PlanHub",
  "project": "Walmart 1820.1009 - Kittanning, PA",
  "region": "Armstrong County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 79,
  "sr": 67,
  "portal": "PlanHub",
  "project": "Walmart 7671.1000 - Seven Fields, PA",
  "region": "Butler County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 80,
  "sr": 68,
  "portal": "PlanHub",
  "project": "S & T Bank, One North Shore, Pittsburgh, PA",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Glass Railing"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 81,
  "sr": 69,
  "portal": "PlanHub",
  "project": "Discount Tire",
  "region": "Fayette County",
  "inRegion": true,
  "products": [],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-08-23",
  "status": "Not Started",
  "comments": "",
  "month": 7,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 82,
  "sr": 70,
  "portal": "BuildingConnected",
  "project": "USPS - Pittsburgh, PA - Retail Lobby Modernization",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 83,
  "sr": 71,
  "portal": "ConstructConnect",
  "project": "Roof Restoration & Building Infrastructure Improvements",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "Steel Guardrail"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "2026-09-20",
  "status": "Not Started",
  "comments": "",
  "month": 8,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 84,
  "sr": 72,
  "portal": "PlanHub",
  "project": "Malden Water Tank Replacement",
  "region": "Washington County",
  "inRegion": true,
  "products": [
   "Steel Handrails"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 85,
  "sr": 73,
  "portal": "PlanHub",
  "project": "Doller Tree, Irwin PA",
  "region": "Westmoreland County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 86,
  "sr": 74,
  "portal": "PlanHub",
  "project": "Wild Birds Unlimited - Wexford, PA",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 87,
  "sr": 75,
  "portal": "ConstructConnect",
  "project": "Ultraviolet System Replacement",
  "region": "Fayette County",
  "inRegion": true,
  "products": [],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 88,
  "sr": 76,
  "portal": "ConstructConnect",
  "project": "PGH Airport - Green Spine Project",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 89,
  "sr": 77,
  "portal": "PlanHub",
  "project": "Rutter's Waynesburg PA",
  "region": "Greene County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 90,
  "sr": 78,
  "portal": "PlanHub",
  "project": "AutoZone #11287 - Monogahela, PA",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 91,
  "sr": 79,
  "portal": "PlanHub",
  "project": "Jim Shorkey Service Center",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 92,
  "sr": 80,
  "portal": "BuildingConnected",
  "project": "OPP-136205 Amazon Quick Commerce ZPA3 - Pittsburgh, PA",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 },
 {
  "id": 93,
  "sr": 81,
  "portal": "ConstructConnect",
  "project": "Sheraden Park Phase 1 Construction",
  "region": "Allegheny County",
  "inRegion": true,
  "products": [
   "No Scope"
  ],
  "material": "",
  "engineer": "",
  "lf": null,
  "price": null,
  "assignedHrs": 0,
  "estHrs": null,
  "bidHrs": null,
  "totalHrs": 0,
  "dueDate": "",
  "status": "Not Started",
  "comments": "",
  "month": 6,
  "takeoffId": null,
  "proposalId": null,
  "priceLocked": false
 }
];
